@echo off
echo Starting production build...

echo Changing to BoardCutter.Client directory...
cd /d "./BoardCutter.Client"

echo Running npm install...
call npm install

echo Running npm build...
call npm run build

echo Changing back to root directory...
cd ..

echo Setting environment to Production...
set ASPNETCORE_ENVIRONMENT=Production

echo Starting .NET application...
dotnet run --project BoardCutter.Web/BoardCutter.Web.csproj --launch-profile testprod
